services:
    - docker

before_install:
    - docker build -t dragon3h/frontend-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true dragon3h/frontend-docker npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "frontend-docker-00"
    env: "FrontendDocker00-env"
    bucket_name: "elasticbeanstalk-us-east-2-868655521662"
    bucket_path: "frontend-docker-00"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY