services:
    - docker

before_install:
    - docker build -t dragon3h/frontend-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true dragon3h/frontend-docker npm run test
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "frontend-docker"
    env: "FrontendDocker-env"
    bucket-name: "elasticbeanstalk-us-east-2-868655521662"
    bucket-path: "frontend-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"