sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dragon3h/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dragon3h/docker-react npm run test -- --coverage

  # safelist
branches:
  only:
  - main