version: '3'

services: 
    web:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "4001:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        stdin_open: true